// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace lab6.Migrations
{
    [DbContext(typeof(GameLibraryContext))]
    [Migration("20251209062120_InitialState")]
    partial class InitialState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Steam.Models.Achievement", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Goal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AchievementId");

                    b.HasIndex("GameId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Steam.Models.AppUser", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("AppUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Steam.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Steam.Models.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GameId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Games", t =>
                        {
                            t.HasCheckConstraint("CK_Game_Price", "\"Price\" > 0");
                        });
                });

            modelBuilder.Entity("Steam.Models.GameCategory", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("GameId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("GameCategories");
                });

            modelBuilder.Entity("Steam.Models.GameCollection", b =>
                {
                    b.Property<Guid>("GameCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserLibraryId")
                        .HasColumnType("uuid");

                    b.HasKey("GameCollectionId");

                    b.HasIndex("UserLibraryId");

                    b.ToTable("GameCollections");
                });

            modelBuilder.Entity("Steam.Models.LibraryCollection", b =>
                {
                    b.Property<Guid>("GameCollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.HasKey("GameCollectionId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("LibraryCollections");
                });

            modelBuilder.Entity("Steam.Models.Progress", b =>
                {
                    b.Property<Guid>("UserLibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("HoursPlayed")
                        .HasColumnType("integer");

                    b.HasKey("UserLibraryId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("Steam.Models.UnlockedAchievement", b =>
                {
                    b.Property<Guid>("UserLibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataComplete")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserLibraryId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UnlockedAchievements");
                });

            modelBuilder.Entity("Steam.Models.UserInfo", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("AppUserId");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("Steam.Models.UserLibrary", b =>
                {
                    b.Property<Guid>("UserLibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserLibraryId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("UserLibraries");
                });

            modelBuilder.Entity("Steam.Models.Achievement", b =>
                {
                    b.HasOne("Steam.Models.Game", "Game")
                        .WithMany("Achievements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Steam.Models.GameCategory", b =>
                {
                    b.HasOne("Steam.Models.Category", "Category")
                        .WithMany("GameCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steam.Models.Game", "Game")
                        .WithMany("GameCategories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Steam.Models.GameCollection", b =>
                {
                    b.HasOne("Steam.Models.UserLibrary", "UserLibrary")
                        .WithMany("GameCollections")
                        .HasForeignKey("UserLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserLibrary");
                });

            modelBuilder.Entity("Steam.Models.LibraryCollection", b =>
                {
                    b.HasOne("Steam.Models.GameCollection", "GameCollection")
                        .WithMany("LibraryCollections")
                        .HasForeignKey("GameCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steam.Models.Game", "Game")
                        .WithMany("LibraryCollections")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameCollection");
                });

            modelBuilder.Entity("Steam.Models.Progress", b =>
                {
                    b.HasOne("Steam.Models.Game", "Game")
                        .WithMany("Progresses")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steam.Models.UserLibrary", "UserLibrary")
                        .WithMany("Progresses")
                        .HasForeignKey("UserLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("UserLibrary");
                });

            modelBuilder.Entity("Steam.Models.UnlockedAchievement", b =>
                {
                    b.HasOne("Steam.Models.Achievement", "Achievement")
                        .WithMany("UnlockedAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steam.Models.UserLibrary", "UserLibrary")
                        .WithMany("UnlockedAchievements")
                        .HasForeignKey("UserLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("UserLibrary");
                });

            modelBuilder.Entity("Steam.Models.UserInfo", b =>
                {
                    b.HasOne("Steam.Models.AppUser", "AppUser")
                        .WithOne("UserInfo")
                        .HasForeignKey("Steam.Models.UserInfo", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Steam.Models.UserLibrary", b =>
                {
                    b.HasOne("Steam.Models.AppUser", "AppUser")
                        .WithOne("UserLibrary")
                        .HasForeignKey("Steam.Models.UserLibrary", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Steam.Models.Achievement", b =>
                {
                    b.Navigation("UnlockedAchievements");
                });

            modelBuilder.Entity("Steam.Models.AppUser", b =>
                {
                    b.Navigation("UserInfo");

                    b.Navigation("UserLibrary");
                });

            modelBuilder.Entity("Steam.Models.Category", b =>
                {
                    b.Navigation("GameCategories");
                });

            modelBuilder.Entity("Steam.Models.Game", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("GameCategories");

                    b.Navigation("LibraryCollections");

                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("Steam.Models.GameCollection", b =>
                {
                    b.Navigation("LibraryCollections");
                });

            modelBuilder.Entity("Steam.Models.UserLibrary", b =>
                {
                    b.Navigation("GameCollections");

                    b.Navigation("Progresses");

                    b.Navigation("UnlockedAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
